export class FlipperIds {
  static readonly MARKER_ACTION_BUTTON = "MARKER_ACTION_BUTTON";
  static readonly MARKER_CARD_HEADER = "MARKER_CARD_HEADER";
  static readonly MARKER_TOOLBAR = "MARKER_TOOLBAR";
  static readonly MARKER_CARD_METRICS = "MARKER_CARD_METRICS";
  static readonly MARKER_MORE_DETAILS_BUTTON = "MARKER_MORE_DETAILS_BUTTON";

  static readonly MAP_CARD = "MAP_CARD";
  static readonly MAP_CARD_CONTAINER = "MAP_CARD_CONTAINER";
  static readonly MORE_DETAILS_CARD = "MORE_DETAILS_CARD";

  static readonly SELECTION_BAR_CONTAINER = "SELECTION_BAR_CONTAINER";
  static readonly BELOW_LEGEND_CONTENT = "BELOW_LEGEND_CONTENT";
  static readonly DRILL_DOWN_TABLE_CONTAINER = "DRILL_DOWN_TABLE_CONTAINER";
  static readonly SELECTION_BAR = "SELECTION_BAR";
}
